<?xml version="1.0" encoding="utf-8"?><Database Class="DBClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.String" CanBeNull="false" />
      <Column Name="Username" Type="System.String" CanBeNull="false" />
      <Column Name="Password" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>